on: push
name: Deploy website on push
jobs:
  web-deploy:
   name: Deploy
   runs-on: ubuntu-latest
   steps:
   - name: Get latest code
     uses: actions/checkout@v2
   
   - name: Sync files
     uses: SamKirkland/FTP-Deploy-Action@4.3.0
     with:
       server: node236-eu.n0c.com
       server-dir: /public_html/mediatekformation-master/
       username: linda@mediatekformation-master.com
       password: ${{ secrets.ftp_password }}
